//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedbackCollection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comment()
        {
            this.CommentsInteractions = new HashSet<CommentsInteraction>();
        }
    
        public int Id { get; set; }
        public int PostId { get; set; }
        public Nullable<int> CommentLike { get; set; }
        public Nullable<int> CommentDislike { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string CommentDesc { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentsInteraction> CommentsInteractions { get; set; }
    }
}
